# Generated by Django 6.0.5 on 2026-07-18 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_organisationactivitylog_taskactivitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationtaskrelationships',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='tasks.organisationtask'),
        ),
    ]
